"""ChargePlus Ingestion Module.

Phase: 2/6 (Real Data Ingestion & Data Quality)
Step: 2.1 (Define Canonical Station/Connector Input Contract)
"""

from backend.ingestion.base import (
    AdapterResult,
    BaseSourceAdapter,
    BatchAdapterResult,
)
from backend.ingestion.adapters.openchargemap import OpenChargeMapAdapter
from backend.ingestion.constants import (
    CONTRACT_VERSION,
    AvailabilityStatus,
    OperationalStatus,
    PricingType,
    QueueLevel,
    StandardConnectorType,
    ValidationOutcome,
)
from backend.ingestion.contracts import (
    NormalizedConnectorRecord,
    NormalizedObservationRecord,
    NormalizedStationRecord,
    ProvenanceInfo,
    RawSourceRecord,
)
from backend.ingestion.validation import (
    BatchValidationReport,
    DataQualityValidator,
    QualityFinding,
    QualityRuleCategory,
    QualitySeverity,
    QuarantineRecord,
    ValidationResult,
)

from backend.ingestion.persistence import (
    BatchCanonicalPersistenceReport,
    CanonicalPersistenceResult,
    CanonicalPersistenceStatus,
    IngestionPersistenceService,
    PersistenceStatus,
    StationPersistenceResult,
)
from backend.ingestion.runner import (
    IngestionRunner,
    IngestionSummary,
)
from backend.ingestion.resolution import (
    AddressEvidence,
    ConnectorEvidence,
    CrossSourceEntityResolver,
    EntityResolutionCandidate,
    EntityResolutionConfig,
    EvidenceSignal,
    GeoProximityEvidence,
    MatchState,
    NameSimilarityEvidence,
    OperatorEvidence,
    haversine_distance_meters,
    normalize_string_for_matching,
)
from backend.ingestion.normalization import (
    NORMALIZATION_VERSION,
    CurrentType,
    DayOfWeek,
    DaySchedule,
    NormalizationStatus,
    NormalizedAddress,
    NormalizedConnector,
    NormalizedCoordinates,
    NormalizedElectrical,
    NormalizedField,
    NormalizedOperatingHours,
    NormalizedOperator,
    NormalizedPricing,
    OperatorMappingType,
    PricingBasis,
    StationNormalizationResult,
    TimeInterval,
    clean_whitespace,
    normalize_address,
    normalize_address_text,
    normalize_amperage,
    normalize_connector_record,
    normalize_connector_type,
    normalize_coordinates,
    normalize_current_type,
    normalize_operating_hours,
    normalize_operator,
    normalize_postal_code,
    normalize_power,
    normalize_pricing,
    normalize_station_record,
    normalize_voltage,
)
from backend.ingestion.deduplication import (
    CanonicalDecisionState,
    CanonicalDeduplicationEngine,
    CanonicalResolutionDecision,
    ExistingCanonicalStation,
    FieldSurvivorshipDecision,
    FieldSurvivorshipPolicy,
    SurvivorshipStrategy,
)
from backend.ingestion.freshness import (
    DEFAULT_LIVE_TELEMETRY_POLICY,
    DEFAULT_OPERATIONAL_STATUS_POLICY,
    DEFAULT_PRICING_POLICY,
    DEFAULT_STATIC_METADATA_POLICY,
    OCM_LIVE_TELEMETRY_POLICY,
    OCM_STATIC_METADATA_POLICY,
    DecayCurve,
    FreshnessBasis,
    FreshnessEngine,
    FreshnessEvaluationResult,
    FreshnessPolicy,
    FreshnessPolicyRegistry,
    FreshnessState,
    InformationType,
    StationFreshnessSummary,
)

__all__ = [
    "CONTRACT_VERSION",
    "AvailabilityStatus",
    "OperationalStatus",
    "PricingType",
    "QueueLevel",
    "StandardConnectorType",
    "ValidationOutcome",
    "RawSourceRecord",
    "ProvenanceInfo",
    "NormalizedConnectorRecord",
    "NormalizedObservationRecord",
    "NormalizedStationRecord",
    "DataQualityValidator",
    "ValidationResult",
    "QualitySeverity",
    "QualityRuleCategory",
    "QualityFinding",
    "QuarantineRecord",
    "BatchValidationReport",
    "BaseSourceAdapter",
    "AdapterResult",
    "BatchAdapterResult",
    "OpenChargeMapAdapter",
    "IngestionPersistenceService",
    "PersistenceStatus",
    "StationPersistenceResult",
    "CanonicalPersistenceStatus",
    "CanonicalPersistenceResult",
    "BatchCanonicalPersistenceReport",
    "IngestionRunner",
    "IngestionSummary",
    "MatchState",
    "EvidenceSignal",
    "GeoProximityEvidence",
    "NameSimilarityEvidence",
    "OperatorEvidence",
    "ConnectorEvidence",
    "AddressEvidence",
    "EntityResolutionCandidate",
    "EntityResolutionConfig",
    "CrossSourceEntityResolver",
    "haversine_distance_meters",
    "normalize_string_for_matching",
    "NORMALIZATION_VERSION",
    "CurrentType",
    "DayOfWeek",
    "DaySchedule",
    "NormalizationStatus",
    "NormalizedAddress",
    "NormalizedConnector",
    "NormalizedCoordinates",
    "NormalizedElectrical",
    "NormalizedField",
    "NormalizedOperatingHours",
    "NormalizedOperator",
    "NormalizedPricing",
    "OperatorMappingType",
    "PricingBasis",
    "StationNormalizationResult",
    "TimeInterval",
    "clean_whitespace",
    "normalize_address",
    "normalize_address_text",
    "normalize_amperage",
    "normalize_connector_record",
    "normalize_connector_type",
    "normalize_coordinates",
    "normalize_current_type",
    "normalize_operating_hours",
    "normalize_operator",
    "normalize_postal_code",
    "normalize_power",
    "normalize_pricing",
    "normalize_station_record",
    "normalize_voltage",
    "CanonicalDecisionState",
    "SurvivorshipStrategy",
    "ExistingCanonicalStation",
    "FieldSurvivorshipDecision",
    "CanonicalResolutionDecision",
    "FieldSurvivorshipPolicy",
    "CanonicalDeduplicationEngine",
    "FreshnessState",
    "FreshnessBasis",
    "InformationType",
    "DecayCurve",
    "FreshnessPolicy",
    "FreshnessEvaluationResult",
    "StationFreshnessSummary",
    "DEFAULT_LIVE_TELEMETRY_POLICY",
    "DEFAULT_OPERATIONAL_STATUS_POLICY",
    "DEFAULT_STATIC_METADATA_POLICY",
    "DEFAULT_PRICING_POLICY",
    "OCM_LIVE_TELEMETRY_POLICY",
    "OCM_STATIC_METADATA_POLICY",
    "FreshnessPolicyRegistry",
    "FreshnessEngine",
]



